Repository StoneHedgeSS13/StoneHedge, pull requests merged in 2024-12, with the labels that each got.

#149 Alot of shit 3
  _maps/map_files/dreamhold/Dreamhold.dmm
  code/__DEFINES/components.dm
  code/__DEFINES/traits.dm
  code/_onclick/item_attack.dm
  code/controllers/subsystem/rogue/devotion.dm
  code/datums/components/_component.dm
  code/datums/gods/patrons/inhumen_pantheon.dm
  code/datums/sexcon/sex_actions/deviant/ear_sex.dm
  code/datums/sexcon/sex_actions/npc/npc_anal_sex.dm
  code/datums/sexcon/sex_actions/oral/blowjob.dm
  code/datums/sexcon/sex_actions/sex/anal_ride_sex.dm
  code/datums/sexcon/sex_actions/sex/vaginal_ride_sex.dm
  code/datums/sexcon/sex_actions/utility/store_nipple.dm
  code/datums/sexcon/sex_actions/utility/store_nipple_other.dm
  code/datums/sexcon/sexcon.dm
  code/datums/status_effects/rogue/debuff.dm
  code/game/objects/items/granters.dm
  code/game/objects/items/rogueweapons/rmb_intents.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/bard.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/cleric.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/mage.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/bladesinger.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/witchhunter.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rogue.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/warlock.dm
  code/modules/jobs/job_types/roguetown/apprentices/mage_apprentice.dm
  code/modules/jobs/job_types/roguetown/church/priest.dm
  code/modules/jobs/job_types/roguetown/church/puritan.dm
  code/modules/jobs/job_types/roguetown/courtier/magician.dm
  code/modules/jobs/job_types/roguetown/youngfolk/mage_apprentice.dm
  code/modules/jobs/jobs.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/living_defense.dm
  code/modules/research/xenobiology/crossbreeding/_potions.dm
  code/modules/surgery/bodyparts/bodypart_wounds.dm
  code/testing.dm
  modular_stonehedge/code/datums/traits/unspecial.dm
  modular_stonehedge/code/game/objects/items/class_selectors.dm
  modular_stonehedge/code/game/objects/items/rogueweapons/reagent_coating.dm
  modular_stonehedge/code/lewdai/lewdai.dm
  modular_stonehedge/code/modules/mob/living/simple_animal/rogue/friendly_npc.dm
  modular_stonehedge/licensed-eaglephntm/icons/mob/screen_alert.dmi
  modular_stonehedge/licensed-eaglephntm/icons/roguetown/items/surgery.dmi
  roguetown.dme
  strings/Anglish.json
Labels: Mapping, Balance, Draft

#156 Jayx Paladins get Misty Step and magic tab
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/donator/paladin.dm
Labels: Balance

#162 Bugfixes Round #1
  _maps/map_files/dreamhold/Dreamhold.dmm
  _maps/map_files/roguetown2/roguetown2.dmm
  code/game/area/roguetownareas.dm
  code/modules/jobs/job_types/roguetown/church/templar.dm
Labels: Mapping, Balance

#175 Makes scythes polearms (and craftable)
  code/modules/farming/tools.dm
  code/modules/jobs/job_types/roguetown/church/mortician.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/weapons.dm
Labels: Balance

#178 Ravenloft Academy Remap (Precursor to #166)
  _maps/map_files/dreamhold/Dreamhold.dmm
  code/controllers/subsystem/rogue/library.dm
  code/modules/clothing/rogueclothes/rings.dm
  code/modules/jobs/job_types/roguetown/apprentices/mage_apprentice.dm
  code/modules/jobs/job_types/roguetown/courtier/magician.dm
  code/modules/jobs/job_types/roguetown/yeomen/archivist.dm
  code/modules/roguetown/roguemachine/wardingcrystal.dm
  code/modules/roguetown/roguemachine/wizard.dm
  code/modules/spells/roguetown/spells5e/spellscrolls.dm
  icons/obj/crystal.dmi
  roguetown.dme
Labels: Mapping, Spriting, Balance

#181 Re-Implements Ravenloft Remap Ovewritten by Direct Commit
  _maps/map_files/dreamhold/Dreamhold.dmm
Labels: Mapping

#182 Gravesingers trained in their own pants
  code/modules/jobs/job_types/roguetown/church/mortician.dm
Labels: Balance

#184 Armor class revert
  code/modules/clothing/rogueclothes/hats.dm
  code/modules/clothing/rogueclothes/pants.dm
  code/modules/jobs/job_types/roguetown/church/mortician.dm
Labels: Balance

#186 Slightly decreased fighter RNG
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/warrior.dm
Labels: Balance

#187 Attempts to make towners relevant
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/apothecarian.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/apothecary.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/carpenter.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/hunter.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/minstrel.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/peasant.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/towndoctor.dm
  modular_stonehedge/code/datums/traits/unspecial.dm
Labels: Balance

#166 Ravenloft Academy Overhaul
  _maps/map_files/dreamhold/Dreamhold.dmm
  code/__DEFINES/jobs.dm
  code/controllers/subsystem/rogue/library.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/items/rogueitems/keys.dm
  code/modules/client/preferences.dm
  code/modules/clothing/rogueclothes/gloves.dm
  code/modules/clothing/rogueclothes/leather/armor.dm
  code/modules/clothing/rogueclothes/leather/hats.dm
  code/modules/clothing/rogueclothes/leather/pants.dm
  code/modules/clothing/rogueclothes/leather/shoes.dm
  code/modules/clothing/rogueclothes/pants.dm
  code/modules/clothing/rogueclothes/wrists.dm
  code/modules/jobs/job_types/roguetown/academy/acadapp.dm
  code/modules/jobs/job_types/roguetown/academy/acadarchmage.dm
  code/modules/jobs/job_types/roguetown/academy/acadmage.dm
  code/modules/jobs/job_types/roguetown/apprentices/mage_apprentice.dm
  code/modules/jobs/job_types/roguetown/courtier/magician.dm
  code/modules/jobs/job_types/roguetown/yeomen/archivist.dm
  code/modules/jobs/jobs.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/roguetown/roguemachine/academy.dm
  code/modules/roguetown/roguemachine/wardingcrystal.dm
  code/modules/roguetown/roguemachine/wizard.dm
  modular_stonehedge/code/game/objects/items/class_selectors.dm
  roguetown.dme
Labels: Mapping, Balance

#188 Buffs and nerfs everything you love.
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/_onclick/other_mobs.dm
  code/datums/gods/patrons/divine_pantheon.dm
  code/datums/gods/patrons/inhumen_pantheon.dm
  code/datums/sexcon/sexcon.dm
  code/game/objects/items/granters.dm
  code/game/objects/items/rogueweapons/ranged/ammo.dm
  code/modules/jobs/job_types/roguetown/academy/acadapp.dm
  code/modules/jobs/job_types/roguetown/academy/acadarchmage.dm
  code/modules/jobs/job_types/roguetown/academy/acadmage.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/antag/hedgeknight.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/bard.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/cleric.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/donator/paladin.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/mage.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/ranger.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/bladesinger.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/sentinel.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/witchhunter.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rogue.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/warlock.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/apothecarian.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/blacksmith.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/carpenter.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/cheesemaker.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/fisher.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/hunter.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/miner.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/minstrel.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/peasant.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/seamstress.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/smuggler.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/thug.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/towndoctor.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/woodcutter.dm
  code/modules/jobs/job_types/roguetown/church/druid.dm
  code/modules/jobs/job_types/roguetown/church/monk.dm
  code/modules/jobs/job_types/roguetown/church/puritan.dm
  code/modules/jobs/job_types/roguetown/church/templar.dm
  code/modules/jobs/job_types/roguetown/goblin/tribalsmith.dm
  code/modules/jobs/job_types/roguetown/goblin/tribalvillager.dm
  code/modules/jobs/job_types/roguetown/mercenaries/sellsword.dm
  code/modules/jobs/job_types/roguetown/nobility/judge.dm
  code/modules/jobs/job_types/roguetown/yeomen/alchemist.dm
  code/modules/jobs/job_types/roguetown/yeomen/barkeep.dm
  code/modules/jobs/job_types/roguetown/yeomen/blacksmith.dm
  code/modules/jobs/job_types/roguetown/yeomen/mason.dm
  code/modules/jobs/job_types/roguetown/yeomen/merchant.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/stats.dm
  code/modules/roguetown/roguecrafting/items.dm
  code/modules/spells/spell.dm
  code/modules/surgery/surgeries/organic_steps.dm
  modular_hearthstone/code/game/objects/effects/dungeon_mob_spawn.dm
  modular_hearthstone/statpacks/physical.dm
  modular_hearthstone/statpacks/wildcard.dm
  modular_stonehedge/code/game/objects/items/class_selectors.dm
Labels: Mapping, Balance

#193 Re-Adds PROSPERO to Map
  _maps/map_files/dreamhold/Dreamhold.dmm
Labels: Mapping

#200 Academy Buffs & Balance Fixes pt. 1
  code/modules/jobs/job_types/roguetown/academy/acadapp.dm
  code/modules/jobs/job_types/roguetown/academy/acadarchmage.dm
  code/modules/jobs/job_types/roguetown/academy/acadmage.dm
  modular_stonehedge/code/game/objects/items/class_selectors.dm
Labels: Balance

#205 Spellslinger armor won't be invisible on women
  icons/roguetown/clothing/onmob/armor.dmi
  icons/roguetown/clothing/onmob/feet.dmi
  icons/roguetown/clothing/onmob/gloves.dmi
Labels: Spriting

#208 Ravenloft Changes Based on Player Feedback
  _maps/map_files/dreamhold/Dreamhold.dmm
  code/modules/cargo/packsrogue/wizardvend/basics.dm
  code/modules/roguetown/roguemachine/wizard.dm
  modular_stonehedge/code/game/objects/items/class_selectors.dm
  roguetown.dme
Labels: Mapping

#204 Leper warrior subtype and more
  code/datums/character_flaw/_character_flaw.dm
  code/datums/status_effects/debuffs.dm
  code/datums/status_effects/rogue/debuff.dm
  code/datums/stress/negative_events.dm
  code/game/objects/items/rogueweapons/melee/polearms.dm
  code/game/objects/items/rogueweapons/melee/swords.dm
  code/modules/clothing/rogueclothes/armor.dm
  code/modules/clothing/rogueclothes/cloaks.dm
  code/modules/clothing/rogueclothes/hats.dm
  code/modules/clothing/rogueclothes/leather/gloves.dm
  code/modules/clothing/rogueclothes/leather/pants.dm
  code/modules/clothing/rogueclothes/mask.dm
  code/modules/clothing/rogueclothes/pants.dm
  code/modules/clothing/rogueclothes/wrists.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/amazon.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/mage.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/knighterrant.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/warrior.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/blacksmith.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/fisher.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/seamstress.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/woodcutter.dm
  code/modules/jobs/job_types/roguetown/yeomen/barkeep.dm
  code/modules/jobs/job_types/roguetown/yeomen/blacksmith.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/armor.dm
  code/modules/spells/roguetown/barbarian.dm
  code/modules/spells/roguetown/fighter.dm
  config/config.txt
  modular_stonehedge/code/datums/traits/unspecial.dm
  modular_stonehedge/icons/mob/screen_alert.dmi
  modular_stonehedge/icons/roguetown/clothing/head.dmi
  modular_stonehedge/icons/roguetown/clothing/masks.dmi
  modular_stonehedge/icons/roguetown/clothing/onmob/head.dmi
  modular_stonehedge/icons/roguetown/clothing/onmob/masks.dmi
  modular_stonehedge/icons/roguetown/weapons/64.dmi
  modular_stonehedge/licensed-eaglephntm/icons/mob/screen_alert.dmi
Labels: Balance

#210 Ports some shit and Bandit hoardmaster
  _maps/map_files/generic/CentCom.dmm
  code/__DEFINES/mobs.dm
  code/game/objects/items/rogueitems/coins.dm
  code/game/objects/obj_defense.dm
  code/game/objects/structures/fluff.dm
  code/game/objects/structures/traveltile.dm
  code/modules/antagonists/roguetown/villain/bandit.dm
  code/modules/cargo/packsrogue/brigand.dm
  code/modules/cargo/packsrogue/foresworn.dm
  code/modules/cargo/packsrogue/hedgeknight.dm
  code/modules/cargo/packsrogue/knave.dm
  code/modules/cargo/packsrogue/mage.dm
  code/modules/cargo/packsrogue/sawbones.dm
  code/modules/cargo/packsrogue/things.dm
  code/modules/clothing/rogueclothes/cloaks.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/antag/brigand.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/antag/foresworn.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/antag/knave.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/antag/sawbones.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/towndoctor.dm
  code/modules/mob/living/carbon/human/species_types/roguetown/other/tiefling.dm
  code/modules/mob/living/simple_animal/friendly/cat.dm
  code/modules/mob/living/simple_animal/rogue/creacher/honeyspider.dm
  code/modules/mob/living/simple_animal/rogue/farm/chicken.dm
  code/modules/mob/living/simple_animal/rogue/game/saiga.dm
  code/modules/roguetown/roguecrafting/items.dm
  code/modules/roguetown/roguecrafting/sewing.dm
  code/modules/roguetown/roguejobs/alchemist/reagents.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/tools.dm
  code/modules/roguetown/roguejobs/cook/tools/pot.dm
  code/modules/roguetown/roguemachine/hoardmaster.dm
  code/modules/roguetown/roguemachine/scomm.dm
  icons/roguetown/clothing/cloaks.dmi
  icons/roguetown/clothing/onmob/cloaks.dmi
  icons/roguetown/items/natural.dmi
  icons/roguetown/misc/96x96.dmi
  modular/Neu_Food/code/raw/NeuFood_dough.dm
  modular_hearthstone/code/game/objects/items/clothes/bell_dress.dm
  roguetown.dme
  sound/misc/hoardmasterpurchase.ogg
Labels: Mapping, Spriting, Balance

#215 Damn, bitch. You sold your soul for this? (AKA, a warlock buff)
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/warlock.dm
Labels: Balance

#213 Minor shit
  code/modules/antagonists/roguetown/roleobjs/purishep.dm
  code/modules/cargo/packsrogue/sawbones.dm
  code/modules/clothing/rogueclothes/armor.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/antag/sawbones.dm
  code/modules/jobs/job_types/roguetown/church/confessor.dm
  code/modules/jobs/job_types/roguetown/church/puritan.dm
  code/modules/mob/living/carbon/human/npc/goblin.dm
  code/modules/roguetown/roguecrafting/leather.dm
  code/modules/roguetown/roguecrafting/sewing.dm
  code/modules/surgery/organs/eyes.dm
  icons/roguetown/clothing/head.dmi
  roguetown.dme
Labels: Spriting, Balance

#216 vamp manor reopen to public
  _maps/map_files/dreamhold/Dreamhold.dmm
Labels: Mapping

#220 A chunk of lore transmogging
  code/__DEFINES/traits.dm
  code/game/objects/effects/glowshroom.dm
  code/game/objects/items/granters.dm
  code/game/objects/items/rogueitems/books.dm
  code/modules/clothing/rogueclothes/hats.dm
  code/modules/clothing/rogueclothes/shirts.dm
  code/modules/farming/soil.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/rare/Lwoodcut.dm
  code/modules/jobs/job_types/roguetown/church/druid.dm
  code/modules/roguetown/roguecrafting/sewing.dm
Labels: Balance

#226 Fix Smithy Apprentice Loadout
  code/modules/jobs/job_types/roguetown/apprentices/smith_apprentice.dm
Labels: Balance

#232 Academy Buffs/Nerfs/Improvements pt. 1
  _maps/map_files/dreamhold/Dreamhold.dmm
  code/game/objects/structures/fluff.dm
  code/game/objects/structures/roguetown/redstone.dm
  code/modules/clothing/rogueclothes/rings.dm
  code/modules/roguetown/roguemachine/academy.dm
  icons/roguetown/clothing/rings.dmi
  modular_stonehedge/code/game/objects/items/class_selectors.dm
Labels: Mapping, Spriting

#235 conflict fix for 848221d
  _maps/map_files/dreamhold/Dreamhold.dmm
Labels: Mapping

#239 Two Bugfixes
  code/modules/jobs/job_types/roguetown/adventurer/types/antag/knave.dm
  code/modules/surgery/bodyparts/bodypart_wounds.dm
Labels: Balance

#247 small tribal QoL
  _maps/map_files/otherz/forest.dmm
Labels: Mapping

#250 Non-Sword Duelist Buffs
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/warrior.dm
Labels: Balance

#249 Sylver Dragon 2.0 - The rebirth of the tavern.
  _maps/map_files/dreamhold/Dreamhold.dmm
  code/game/objects/items/rogueitems/keyrings.dm
  code/game/objects/items/rogueitems/keys.dm
  code/modules/jobs/job_types/roguetown/peasants/butcher.dm
  code/modules/jobs/job_types/roguetown/peasants/cook.dm
  code/modules/jobs/job_types/roguetown/yeomen/barkeep.dm
  code/modules/roguetown/roguemachine/vendor.dm
Labels: Mapping, Balance

#254 Academy Security Upgrade
  _maps/map_files/dreamhold/Dreamhold.dmm
  code/modules/roguetown/roguemachine/academy.dm
Labels: Mapping

#251 Sylver Tavern 2.0 - Innkeeper's room quick fix
  _maps/map_files/dreamhold/Dreamhold.dmm
Labels: Mapping

#264 Grove Testmerge Feedback Fixes
  _maps/map_files/dreamhold/Dreamhold.dmm
  code/__DEFINES/jobs.dm
  code/__DEFINES/traits.dm
  code/game/objects/items/rogueweapons/melee/polearms.dm
  code/game/objects/items/rogueweapons/melee/special.dm
  code/modules/jobs/job_types/roguetown/adventurer/bandit.dm
  code/modules/jobs/job_types/roguetown/breugrove/druid.dm
  code/modules/jobs/job_types/roguetown/breugrove/greatdruid.dm
  code/modules/jobs/job_types/roguetown/breugrove/hedgeknight.dm
  code/modules/jobs/job_types/roguetown/breugrove/hedgewarden.dm
  code/modules/jobs/job_types/roguetown/breugrove/ovate.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/roguetown/roguemachine/ATM.dm
  code/modules/roguetown/roguemachine/_roguemachine.dm
  code/modules/roguetown/roguemachine/academy.dm
  code/modules/roguetown/roguemachine/grove.dm
  modular_stonehedge/code/datums/traits/unspecial.dm
  modular_stonehedge/code/modules/mob/living/simple_animal/rogue/friendly_npc.dm
Labels: Mapping, Balance

#269 Combattante Duelist Merc and New Quirk
  code/modules/jobs/job_types/roguetown/mercenaries/mercenary.dm
  icons/roguetown/clothing/head.dmi
  icons/roguetown/clothing/onmob/head.dmi
  icons/roguetown/weapons/32.dmi
  modular_stonehedge/code/datums/traits/unspecial.dm
  modular_stonehedge/code/game/objects/items/rogueweapons/melee/swords.dm
  modular_stonehedge/code/modules/clothings/rogueclothes/armor.dm
  modular_stonehedge/code/modules/clothings/rogueclothes/hat.dm
  modular_stonehedge/code/modules/clothings/rogueclothes/pants.dm
  modular_stonehedge/code/modules/clothings/rogueclothes/shoes.dm
  modular_stonehedge/code/modules/jobs/job_types/roguetown/mercenaries/classes/combattante.dm
  roguetown.dme
Labels: Spriting, Balance

#271 Quick spelling fix for combattante
  code/modules/clothing/rogueclothes/cloaks.dm
  icons/roguetown/clothing/onmob/cloaks.dmi
  modular_stonehedge/code/game/objects/items/rogueweapons/melee/swords.dm
  modular_stonehedge/code/modules/clothings/rogueclothes/hat.dm
  modular_stonehedge/code/modules/clothings/rogueclothes/pants.dm
  modular_stonehedge/code/modules/clothings/rogueclothes/shoes.dm
Labels: Spriting

#272 Bandit Magic
  code/modules/jobs/job_types/roguetown/adventurer/types/antag/banditmage.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/antag/brigand.dm
  code/modules/roguetown/roguemachine/hoardmaster.dm
  roguetown.dme
Labels: Balance

#278 Grove Feedback Changes pt.2
  code/game/objects/items/rogueweapons/melee/special.dm
  code/modules/clothing/rogueclothes/hats.dm
  code/modules/clothing/rogueclothes/robes.dm
  code/modules/jobs/job_types/roguetown/breugrove/druid.dm
  code/modules/jobs/job_types/roguetown/breugrove/greatdruid.dm
  code/modules/jobs/job_types/roguetown/breugrove/hedgeknight.dm
  code/modules/jobs/job_types/roguetown/breugrove/hedgewarden.dm
  code/modules/roguetown/roguemachine/grove.dm
  modular_stonehedge/code/datums/traits/unspecial.dm
  modular_stonehedge/code/modules/mob/living/simple_animal/rogue/friendly_npc.dm
Labels: Balance

#279 Soilson's Rebirth + Innkeeper's doors fix
  _maps/map_files/dreamhold/Dreamhold.dmm
Labels: Mapping

#287 Tavern upgrade + Fermentation tweaks, attempt 2
  _maps/map_files/dreamhold/Dreamhold.dmm
  code/modules/farming/fermenting_barrel.dm
  code/modules/farming/produce.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
Labels: Mapping

#284 Bug Fixes and Stuff pt. 1
  code/datums/migrants/migrant_waves/slaver roles.dm
  code/game/objects/items/rogueweapons/melee/special.dm
  code/modules/clothing/rogueclothes/hats.dm
  code/modules/clothing/rogueclothes/neck.dm
  code/modules/jobs/job_types/roguetown/breugrove/druid.dm
  code/modules/jobs/job_types/roguetown/breugrove/greatdruid.dm
  code/modules/jobs/job_types/roguetown/breugrove/hedgeknight.dm
  code/modules/jobs/job_types/roguetown/breugrove/hedgewarden.dm
  code/modules/jobs/job_types/roguetown/breugrove/ovate.dm
  code/modules/jobs/job_types/roguetown/peasants/bogprisoner.dm
  code/modules/jobs/job_types/roguetown/peasants/lunatic.dm
  code/modules/jobs/job_types/roguetown/peasants/prisoner.dm
  code/modules/jobs/job_types/roguetown/peasants/town slave.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/roguetown/roguemachine/academy.dm
  code/modules/roguetown/roguemachine/bounty.dm
  code/modules/roguetown/roguemachine/grove.dm
Labels: Balance

#283 Bandit Mage learning
  code/modules/jobs/job_types/roguetown/adventurer/types/antag/banditmage.dm
Labels: Balance

#286 Torsion magic for Archmages
  code/modules/jobs/job_types/roguetown/academy/acadarchmage.dm
Labels: Balance

#256 Craft skills modify 2: Electric Boogaloo
  code/datums/skills/craft.dm
Labels: Balance, testmerge candidate

#290 Tailor's rebirth + Tavern tiny edits
  _maps/map_files/dreamhold/Dreamhold.dmm
  code/__DEFINES/jobs.dm
  code/game/objects/items/rogueitems/keys.dm
  code/modules/farming/fermenting_barrel.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/seamstress.dm
  code/modules/jobs/job_types/roguetown/yeomen/tailor.dm
Labels: Mapping, Balance

#291 Crazy shit brought to you by vide
  code/__HELPERS/time.dm
  code/_onclick/item_attack.dm
  code/controllers/subsystem/particle_weather.dm
  code/controllers/subsystem/rogue/combat_tab.dm
  code/datums/particle_weathers/datum_types/rain.dm
  code/datums/particle_weathers/datum_types/snow_storm.dm
  code/datums/weather/weather_types/roguetown/fog.dm
  code/datums/weather/weather_types/snow_storm.dm
  code/game/objects/items/granters.dm
  code/game/turfs/open/floor/roguefloor.dm
  code/modules/client/preferences_toggles.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/mage.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/necromancer.dm
  code/modules/mob/dead/new_player/sprite_accessory/tail_features.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_wounds.dm
  code/modules/mob/living/stats.dm
  code/modules/roguetown/roguejobs/alchemist/reagents.dm
  code/modules/spells/roguetown/fighter.dm
  code/modules/spells/roguetown/necromancer.dm
  code/modules/surgery/organs/filling_organ.dm
  modular_hearthstone/code/game/objects/effects/dungeon_chest.dm
  modular_stonehedge/code/game/objects/structures/dungeon/loot_generators/dungeon_chest.dm
Labels: Balance

#294 Bugfixes and Stuff pt. 2
  _maps/map_files/dreamhold/Dreamhold.dmm
  code/__DEFINES/traits.dm
  code/_onclick/other_mobs.dm
  code/modules/clothing/rogueclothes/neck.dm
  code/modules/roguetown/roguemachine/bounty.dm
  code/modules/roguetown/roguemachine/grove.dm
  modular_stonehedge/code/game/objects/items/class_selectors.dm
Labels: Mapping

#297 nerfs everything you love and some other things
  _maps/map_files/dreamhold/Dreamhold.dmm
  code/datums/components/infusions.dm
  code/datums/particle_weathers/datum_types/snow_storm.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/bladesinger.dm
  code/modules/roguetown/roguemachine/bounty.dm
  code/modules/spells/spell_types/ethereal_jaunt.dm
  modular_hearthstone/icons/mob/newminotaur.dmi
  modular_hearthstone/icons/obj/items/mino_head.dmi
Labels: Mapping, Balance

#292 Update goblin.dm
  code/modules/mob/living/carbon/human/npc/goblin.dm
Labels: Balance, testmerge candidate

#295 Curse quirk changes, Summon Familliar fix, etc
  code/__DEFINES/traits.dm
  code/datums/gods/patrons/curses.dm
  code/modules/antagonists/roguetown/villain/maniac/maniac_life.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/warrior.dm
  code/modules/spells/roguetown/warlock.dm
  icons/roguetown/maniac/dreamer_mobs.dmi
  modular_stonehedge/code/datums/traits/unspecial.dm
  modular_stonehedge/code/modules/jobs/job_types/roguetown/mercenaries/classes/combattante.dm
  strings/maniac.json
Labels: Spriting, Balance

#299 fix warrior's traits and cursed quirk change
  code/controllers/subsystem/processing/quirks.dm
  code/datums/gods/patrons/curses.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/warrior.dm
  modular_stonehedge/code/datums/traits/unspecial.dm
Labels: Balance

#300 ports a tonna shit and some dungeons added
  _maps/map_files/dreamhold/Dreamhold.dmm
  _maps/map_files/dungeons/lichmap.dm
  _maps/map_files/dungeons/lichmap.dmm
  _maps/map_files/dungeons/lichmap.json
  code/__DEFINES/roguetown.dm
  code/controllers/subsystem/mapping.dm
  code/game/area/roguetownareas.dm
  code/game/objects/effects/landmarks.dm
  code/game/turfs/open/floor/roguefloor.dm
  code/modules/jobs/job_types/roguetown/mercenaries/Classes/grenzelhoft.dm
  code/modules/jobs/job_types/roguetown/mercenaries/merch_merc.dm
  code/modules/jobs/job_types/roguetown/peasants/bathmaid.dm
  code/modules/jobs/job_types/roguetown/peasants/nightman.dm
  code/modules/jobs/jobs.dm
  code/modules/language/roguetown/grenzelhoftian.dm
  code/modules/library/lib_items.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/human/species_types/furry/demihuman.dm
  code/modules/mob/living/carbon/human/species_types/roguetown/human/humen.dm
  code/modules/mob/living/simple_animal/friendly/cat.dm
  code/modules/mob/living/simple_animal/friendly/fox.dm
  code/modules/mob/living/simple_animal/rogue/creacher/volf.dm
  code/modules/power/roguelighting.dm
  code/modules/reagents/reagent_containers/bottle.dm
  code/modules/roguetown/roguecrafting/leather.dm
  code/modules/roguetown/roguejobs/gravedigger/hole.dm
  code/modules/spells/roguetown/acolyte/pestra.dm
  code/modules/surgery/organs/tongue.dm
  icons/roguetown/misc/lighting.dmi
  icons/turf/areas.dmi
  icons/turf/roguefloor.dmi
  modular_azurepeak/code/game/objects/items/gwstrap.dm
  modular_azurepeak/icons/obj/items/gwstrap.dmi
  modular_hearthstone/code/modules/mob/living/simple_animal/rogue/orc.dm
  modular_hearthstone/icons/mob/simple_orcs.dmi
  roguetown.dme
  sound/music/area/druid.ogg
Labels: Mapping, Spriting, Balance

#302 Small tribal changes
  _maps/map_files/otherz/forest.dmm
Labels: Mapping

#312 Spawner adjustments
  _maps/map_files/dreamhold/Dreamhold.dmm
  code/game/objects/structures/roguetown/mobspawner.dm
Labels: Mapping

#313 Comments out two lines that shouldn't be used in hood proc
  code/modules/clothing/rogueclothes/hats.dm
Labels: testmerge candidate

#325 adds mining skill to dwarf artificer
  code/modules/jobs/job_types/roguetown/viking/highking.dm
Labels: Balance

#328 buffing acrhfey patron
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/warlock.dm
  code/modules/spells/roguetown/archfey_warlock.dm
Labels: Balance

#321 Henchman fix, Nerf to bouncer, 'fixed' strangling
  code/modules/jobs/job_types/roguetown/mercenaries/merch_merc.dm
  code/modules/mob/living/grabbing.dm
Labels: Balance

#335 Guild Physician part 2
  _maps/map_files/dreamhold/Dreamhold.dmm
  code/game/objects/items/rogueitems/keyrings.dm
  code/game/objects/items/rogueitems/keys.dm
  code/modules/jobs/job_types/roguetown/courtier/physician.dm
  code/modules/roguetown/roguejobs/alchemist/reagents.dm
  modular_stonehedge/code/game/objects/structures/dungeon/loot_generators/dungeon_chest.dm
Labels: Mapping, Balance

#340 ORC RAIDERS
  code/modules/clothing/rogueclothes/npc/orc.dm
  code/modules/mob/living/carbon/human/npc/goblin.dm
  code/modules/mob/living/carbon/human/npc/orc_raider.dm
  code/modules/mob/living/carbon/human/voicepacks/other/orc_raider.dm
  icons/roguetown/mob/monster/Orc.dmi
  roguetown.dme
Labels: Mapping, Spriting

#347 Battle Master Fix
  code/modules/clothing/rogueclothes/wrists.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/donator/paladin.dm
Labels: Balance

#341 Add Trufflepig, Lock Transmutation.
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/datums/components/crafting/crafting.dm
  code/datums/components/crafting/recipes.dm
  code/game/objects/items/rogueitems/bait.dm
  code/game/objects/structures/spawner.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/sorceress.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/warlock.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/apothecarian.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/apothecary.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/towndoctor.dm
  code/modules/jobs/job_types/roguetown/breugrove/druid.dm
  code/modules/jobs/job_types/roguetown/breugrove/greatdruid.dm
  code/modules/jobs/job_types/roguetown/courtier/physician.dm
  code/modules/jobs/job_types/roguetown/goblin/tribalshaman.dm
  code/modules/roguetown/roguecrafting/alchemy.dm
  code/modules/roguetown/roguecrafting/transmutation.dm
  modular/Neu_Food/code/raw/NeuFood_meat.dm
  modular/icons/code/trufflepig.dm
  modular_stonehedge/code/game/objects/items/class_selectors.dm
  roguetown.dme
Labels: Balance

#355 Give Gravesinger key to the temple, take away useless alembic
  code/modules/jobs/job_types/roguetown/church/mortician.dm
Labels: Balance

#362 fixes guidance
  code/controllers/subsystem/rogue/magic_tab.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/cleric.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/warlock.dm
  code/modules/jobs/job_types/roguetown/church/priest.dm
  code/modules/spells/roguetown/spells5e/cantrips5e.dm
  code/modules/spells/roguetown/spells5e/spellscrolls.dm
  modular_hearthstone/code/modules/spells/roguetown/wizard.dm
  modular_stonehedge/code/game/objects/items/class_selectors.dm
Labels: Balance
