Repository StoneHedgeSS13/StoneHedge, pull requests merged in 2024-11, with the labels that each got.

#118 Youngmaster
  code/modules/jobs/job_types/roguetown/church/grandmaster.dm
Labels: Balance

#123 Adds town guards to map
  _maps/map_files/dreamhold/Dreamhold.dmm
Labels: Mapping

#127 various bug fixs, nerf and reworks. and a map oversight.
  _maps/templates/shelter_2.dmm
  code/controllers/subsystem/rogue/devotion.dm
  code/datums/gods/patrons/inhumen_pantheon.dm
  code/game/objects/structures/crates_lockers/roguetown.dm
  code/modules/jobs/job_types/roguetown/adventurer/adventurer.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/ranger.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/rogue.dm
  code/modules/mining/lavaland/necropolis_chests.dm
  code/modules/mob/living/carbon/human/species_types/furry/anthromorphsmall.dm
  code/modules/mob/living/carbon/human/species_types/furry/kobold.dm
  code/modules/spells/roguetown/spells5e/cantrips5e.dm
  modular_hearthstone/statpacks/agile.dm
  modular_stonehedge/code/datums/traits/unspecial.dm
  modular_stonehedge/code/game/objects/items/class_selectors.dm
  modular_stonehedge/code/game/objects/structures/dungeon/loot_generators/dungeon_chest.dm
Labels: Mapping, Balance

#124 Alot of shit again
  _maps/map_files/dreamhold/Dreamhold.dmm
  code/datums/sexcon/sex_actions/npc/npc_anal_ride_sex.dm
  code/datums/sexcon/sex_actions/npc/npc_anal_sex.dm
  code/datums/sexcon/sex_actions/npc/npc_cunnilingus.dm
  code/datums/sexcon/sex_actions/npc/npc_facesitting.dm
  code/datums/sexcon/sex_actions/npc/npc_rimming.dm
  code/datums/sexcon/sex_actions/npc/npc_throat_sex.dm
  code/datums/sexcon/sex_actions/npc/npc_vaginal_ride_sex.dm
  code/datums/sexcon/sex_actions/npc/npc_vaginal_sex.dm
  code/datums/sexcon/sexcon.dm
  code/datums/status_effects/rogue/debuff.dm
  code/game/objects/effects/glowshroom.dm
  code/game/objects/items/rogueweapons/melee/special.dm
  code/modules/jobs/job_types/roguetown/garrison/bogguard.dm
  code/modules/jobs/job_types/roguetown/garrison/bogmaster.dm
  code/modules/mob/living/carbon/human/npc/_npc.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/megafauna.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/mob.dm
  code/modules/surgery/bodyparts/bodypart_examine.dm
  modular_hearthstone/code/game/objects/items/signal_horn.dm
  modular_hearthstone/code/modules/mob/living/simple_animal/rogue/simple_skeleton.dm
  modular_helmsguard/code/game/objects/items/war_horn.dm
  modular_stonehedge/code/datums/traits/unspecial.dm
  modular_stonehedge/code/lewdai/lewdai.dm
  modular_stonehedge/code/modules/mob/living/simple_animal/rogue/friendly_npc.dm
Labels: Mapping, Balance

#134 Expansion of Gravesinger, Part 1
  code/__DEFINES/traits.dm
  code/controllers/subsystem/rogue/treasury.dm
  code/modules/clothing/rogueclothes/mask.dm
  code/modules/clothing/rogueclothes/wrists.dm
  code/modules/farming/tools.dm
  code/modules/jobs/job_types/roguetown/church/mortician.dm
  code/modules/language/language_holder.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/spells/roguetown/acolyte/necra.dm
Labels: Balance

#146 NPC goblin armor fix
  code/modules/clothing/rogueclothes/npc/goblin.dm
  code/modules/jobs/job_types/roguetown/goblin/tribalcook.dm
  code/modules/jobs/job_types/roguetown/goblin/tribalsmith.dm
  code/modules/mob/living/carbon/human/npc/goblin.dm
Labels: Balance

#145 Adds secular diagnosis to the medical training quirk and healing warlocks
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/warlock.dm
  modular_stonehedge/code/datums/traits/unspecial.dm
Labels: Balance

#152 Adds Magician Apprentice Spells to Magician
  code/modules/jobs/job_types/roguetown/courtier/magician.dm
Labels: Balance
